variables:
  - &install_pnpm "npm i -g corepack@latest && corepack enable pnpm"

steps:
  install:
    image: node:alpine
    commands:
      - *install_pnpm
      - pnpm i
    when:
      - event: pull_request

  tsoa:
    image: node:alpine
    commands:
      - *install_pnpm
      - pnpm tsoa
    when:
      - event: pull_request

  lint:
    image: node:alpine
    commands:
      - *install_pnpm
      - pnpm lint
    when:
      - event: pull_request

  npm_publish:
    image: node:alpine
    environment:
      NPM_TOKEN:
        from_secret: npm_token
    commands:
      - *install_pnpm
      - pnpm i
      - echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" >> .npmrc
      - echo "email = tyhou13@gmx.com" >> ~/.npmrc
      - npm publish --tag latest
    when:
      - event: tag

  notify_success:
    image: alpine:3
    commands:
      - apk add curl
      - "curl -H'Title: ✔️ ${CI_REPO_NAME}/${CI_COMMIT_SOURCE_BRANCH}' -d'${CI_PIPELINE_URL}' ntfy.sh/lemmy_drone_ci"
    when:
      - event: pull_request
        status: [success]

  notify_failure:
    image: alpine:3
    commands:
      - apk add curl
      - "curl -H'Title: ❌ ${CI_REPO_NAME}/${CI_COMMIT_SOURCE_BRANCH}' -d'${CI_PIPELINE_URL}' ntfy.sh/lemmy_drone_ci"
    when:
      - event: pull_request
        status: [failure]

  notify_on_tag_deploy:
    image: alpine:3
    commands:
      - apk add curl
      - "curl -H'Title: ${CI_REPO_NAME}:${CI_COMMIT_TAG} deployed' -d'${CI_PIPELINE_URL}' ntfy.sh/lemmy_drone_ci"
    when:
      event: tag
