variables:
  - &install_pnpm "corepack enable pnpm"

steps:
  install:
    image: node:alpine
    commands:
      - *install_pnpm
      - pnpm i
    when:
      - event: pull_request

  tsoa:
    image: node:alpine
    commands:
      - *install_pnpm
      - pnpm tsoa
    when:
      - event: pull_request

  lint:
    image: node:alpine
    commands:
      - *install_pnpm
      - pnpm lint
    when:
      - event: pull_request

  npm_publish:
    image: node:alpine
    environment:
      NPM_TOKEN:
        from_secret: npm_token
    commands:
      - *install_pnpm
      - pnpm i
      - echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" >> .npmrc
      - echo "email = tyhou13@gmx.com" >> ~/.npmrc
      - npm publish --tag latest
    when:
      - event: tag

  notify_on_build:
    image: node:alpine
    commands:
      - apk add curl
      - "curl -d'lemmy-js-client build ${CI_PIPELINE_STATUS}: ${CI_PIPELINE_URL}' ntfy.sh/lemmy_drone_ci"
    when:
      - event: [pull_request, tag]
        status: [failure, success]

  notify_on_tag_deploy:
    image: node:alpine
    commands:
      - apk add curl
      - "curl -d'lemmy-js-client:${CI_COMMIT_TAG} deployed' ntfy.sh/lemmy_drone_ci"
    when:
      - event: tag
