variables:
  - &install_pnpm "corepack enable pnpm"

steps:
  install:
    image: node:alpine
    commands:
      - *install_pnpm
      - pnpm i

  lint:
    image: node:alpine
    commands:
      - *install_pnpm
      - pnpm lint

  npm_publish:
    image: node:alpine
    commands:
      - *install_pnpm
      - echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" >> .npmrc
      - echo "email = tyhou13@gmx.com" >> ~/.npmrc
      - npm publish
    secrets: [npm_token]
    when:
      event: tag
