pipeline:
  yarn:
    image: node:17-alpine
    commands:
      - yarn

  yarn_lint:
    image: node:17-alpine
    commands:
      - yarn lint

  npm_publish:
    image: node:17-alpine
    commands:
      - echo "//registry.npmjs.org/:_authToken=$NPM_AUTH_TOKEN" >> .npmrc
      - echo "email = $NPM_EMAIL" >> ~/.npmrc
      - npm publish
    environment:
      NPM_AUTH_TOKEN:
        from_secret: npm_token
      NPM_EMAIL: tyhou13@gmx.com
    when:
      event: tag
