// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { PersonId } from "./PersonId";

export interface AddAdmin {
  person_id: PersonId;
  added: boolean;
  auth: string;
}
