// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { PersonView } from "./PersonView";

/**
 * The response of current admins.
 */
export type AddAdminResponse = { admins: Array<PersonView> };
