// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { LocalUserId } from "./LocalUserId";

export interface AddAdmin {
  local_user_id: LocalUserId;
  added: boolean;
  auth: string;
}
