// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CommunityModeratorView } from "./CommunityModeratorView";

/**
 * The response of adding a moderator to a community.
 */
export type AddModToCommunityResponse = {
  moderators: Array<CommunityModeratorView>;
};
