// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AdminBlockInstanceId } from "./AdminBlockInstanceId";
import type { InstanceId } from "./InstanceId";
import type { PersonId } from "./PersonId";

export type AdminBlockInstance = {
  id: AdminBlockInstanceId;
  instance_id: InstanceId;
  admin_person_id: PersonId;
  blocked: boolean;
  reason?: string;
  expires_at?: string;
  published_at: string;
};
