// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AdminAddId } from "./AdminAddId";
import type { PersonId } from "./PersonId";

/**
 * When someone is added as a site admin.
 */
export type AdminAdd = {
  id: AdminAddId;
  mod_person_id: PersonId;
  other_person_id: PersonId;
  removed: boolean;
  published_at: string;
};
