// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { InstanceId } from "./InstanceId";

export type AdminAllowInstanceParams = {
  instance_id: InstanceId;
  allow: boolean;
  reason?: string;
};
