// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AdminPurgePerson } from "./AdminPurgePerson";
import type { Person } from "./Person";

/**
 * When an admin purges a person.
 */
export type AdminPurgePersonView = {
  admin_purge_person: AdminPurgePerson;
  admin?: Person;
};
