// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AdminAllowInstance } from "./AdminAllowInstance";
import type { Instance } from "./Instance";
import type { Person } from "./Person";

/**
 * When an admin purges a post.
 */
export type AdminAllowInstanceView = {
  admin_allow_instance: AdminAllowInstance;
  instance: Instance;
  admin?: Person;
};
