// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AdminBanId } from "./AdminBanId";
import type { InstanceId } from "./InstanceId";
import type { PersonId } from "./PersonId";

/**
 * When someone is banned from the site.
 */
export type AdminBan = {
  id: AdminBanId;
  mod_person_id: PersonId;
  other_person_id: PersonId;
  reason: string;
  banned: boolean;
  expires_at?: string;
  published_at: string;
  instance_id: InstanceId;
};
