// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AdminPurgeCommunityId } from "./AdminPurgeCommunityId";
import type { PersonId } from "./PersonId";

/**
 * When an admin purges a community.
 */
export type AdminPurgeCommunity = {
  id: AdminPurgeCommunityId;
  admin_person_id: PersonId;
  reason?: string;
  when_: string;
};
