// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AdminBlockInstance } from "./AdminBlockInstance";
import type { Instance } from "./Instance";
import type { Person } from "./Person";

/**
 * When an admin purges a post.
 */
export type AdminBlockInstanceView = {
  admin_block_instance: AdminBlockInstance;
  instance: Instance;
  admin?: Person;
};
