// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { InstanceId } from "./InstanceId";
import type { PersonId } from "./PersonId";

export type AdminBlockInstance = {
  id: number;
  instance_id: InstanceId;
  admin_person_id: PersonId;
  blocked: boolean;
  reason?: string;
  expires?: string;
  published: string;
};
