// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AdminAdd } from "./AdminAdd";
import type { Person } from "./Person";

/**
 * When someone is added as a site moderator.
 */
export type AdminAddView = {
  admin_add: AdminAdd;
  moderator?: Person;
  other_person: Person;
};
