// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AdminRemoveCommunity } from "./AdminRemoveCommunity";
import type { Community } from "./Community";
import type { Person } from "./Person";

/**
 * When an admin removes a community.
 */
export type AdminRemoveCommunityView = {
  admin_remove_community: AdminRemoveCommunity;
  moderator?: Person;
  community: Community;
};
