// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AdminAllowInstanceId } from "./AdminAllowInstanceId";
import type { InstanceId } from "./InstanceId";
import type { PersonId } from "./PersonId";

export type AdminAllowInstance = {
  id: AdminAllowInstanceId;
  instance_id: InstanceId;
  admin_person_id: PersonId;
  allowed: boolean;
  reason?: string;
  when_: string;
};
