// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { PersonId } from "./PersonId";

/**
 * When an admin purges a person.
 */
export type AdminPurgePerson = {
  id: number;
  admin_person_id: PersonId;
  reason?: string;
  when_: string;
};
