// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type AdminBlockInstanceParams = {
  instance: string;
  block: boolean;
  reason: string;
  /**
   * A time that the block will expire, in unix epoch seconds.
   *
   * An i64 unix timestamp is used for a simpler API client implementation.
   */
  expires_at?: number;
};
