// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AdminPurgeCommunity } from "./AdminPurgeCommunity";
import type { Person } from "./Person";

/**
 * When an admin purges a community.
 */
export type AdminPurgeCommunityView = {
  admin_purge_community: AdminPurgeCommunity;
  admin?: Person;
};
