// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { InstanceIdOrDomain } from "./InstanceIdOrDomain";

export type AdminBlockInstanceParams = {
  instance: InstanceIdOrDomain;
  block: boolean;
  reason?: string;
  expires?: string;
};
