// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { LocalUserSortType } from "./LocalUserSortType";
import type { PaginationCursor } from "./PaginationCursor";

export type AdminListUsers = {
  banned_only?: boolean;
  page_cursor?: PaginationCursor;
  sort?: LocalUserSortType;
  limit?: number;
};
