// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AdminBan } from "./AdminBan";
import type { Person } from "./Person";

/**
 * When someone is banned from the site.
 */
export type AdminBanView = {
  admin_ban: AdminBan;
  moderator?: Person;
  other_person: Person;
};
