// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { RegistrationApplicationId } from "./RegistrationApplicationId";

/**
 * Approves a registration application.
 */
export type ApproveRegistrationApplication = {
  id: RegistrationApplicationId;
  approve: boolean;
  deny_reason?: string;
};
