// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CommunityId } from "./CommunityId";
import type { PersonId } from "./PersonId";

export interface ApproveCommunityPendingFollows {
  community_id: CommunityId;
  follower_id: PersonId;
  approve: boolean;
}
