// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export interface AuthenticateWithOauth {
  code: string;
  oauth_provider_id: string;
  redirect_uri: string;
  show_nsfw?: boolean;
  answer?: string;
}
