// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { PersonView } from "./PersonView";

/**
 * The response for banning a user from a community.
 */
export type BanFromCommunityResponse = {
  person_view: PersonView;
  banned: boolean;
};
