// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { PersonView } from "./PersonView";

/**
 * The list of banned persons.
 */
export type BannedPersonsResponse = { banned: Array<PersonView> };
