// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { PersonView } from "./PersonView";

/**
 * A response for a banned person.
 */
export type BanPersonResponse = { person_view: PersonView; banned: boolean };
