// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CommunityView } from "./CommunityView";

/**
 * The block community response.
 */
export type BlockCommunityResponse = {
  community_view: CommunityView;
  blocked: boolean;
};
