// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { PersonId } from "./PersonId";

/**
 * Block a person.
 */
export type BlockPerson = { person_id: PersonId; block: boolean };
