// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { PersonView } from "./PersonView";

/**
 * The response for a person block.
 */
export type BlockPersonResponse = { person_view: PersonView; blocked: boolean };
