// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CommunityReportView } from "./CommunityReportView";

/**
 * A community report response.
 */
export type CommunityReportResponse = {
  community_report_view: CommunityReportView;
};
