// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CommentView } from "./CommentView";
import type { LocalUserId } from "./LocalUserId";

export interface CommentResponse {
  comment_view: CommentView;
  recipient_ids: Array<LocalUserId>;
  form_id?: string;
}
