// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * The community sort types. See here for descriptions: https://join-lemmy.org/docs/en/users/03-votes-and-ranking.html
 */
export type CommunitySortType =
  | "Active"
  | "Hot"
  | "New"
  | "Old"
  | "TopDay"
  | "TopWeek"
  | "TopMonth"
  | "TopYear"
  | "TopAll"
  | "MostComments"
  | "NewComments"
  | "TopHour"
  | "TopSixHour"
  | "TopTwelveHour"
  | "TopThreeMonths"
  | "TopSixMonths"
  | "TopNineMonths"
  | "Controversial"
  | "Scaled"
  | "NameAsc"
  | "NameDesc";
