// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CommentId } from "./CommentId";
import type { PersonId } from "./PersonId";

export type CommentActions = {
  person_id: PersonId;
  comment_id: CommentId;
  like_score?: number;
  liked?: string;
  saved?: string;
};
