// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CommunityView } from "./CommunityView";
import type { LanguageId } from "./LanguageId";

export interface CommunityResponse {
  community_view: CommunityView;
  discussion_languages: Array<LanguageId>;
}
