// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CommunityFollowerState } from "./CommunityFollowerState";

export type CommunityActions = {
  /**
   * When the community was followed.
   */
  followed?: string;
  /**
   * The state of the community follow.
   */
  follow_state?: CommunityFollowerState;
  /**
   * When the community was blocked.
   */
  blocked?: string;
  /**
   * When this user became a moderator.
   */
  became_moderator?: string;
  /**
   * When this user received a ban.
   */
  received_ban?: string;
  /**
   * When their ban expires.
   */
  ban_expires?: string;
};
