// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CommentId } from "./CommentId";

export interface CommentAggregates {
  comment_id: CommentId;
  score: /* integer */ number;
  upvotes: /* integer */ number;
  downvotes: /* integer */ number;
  published: string;
  child_count: number;
}
