// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Community } from "./Community";
import type { CommunityActions } from "./CommunityActions";
import type { CommunityTagsView } from "./CommunityTagsView";

/**
 * A community view.
 */
export type CommunityView = {
  community: Community;
  community_actions?: CommunityActions;
  can_mod: boolean;
  tags: CommunityTagsView;
};
