// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Comment } from "./Comment";
import type { CommentActions } from "./CommentActions";
import type { CommunityActions } from "./CommunityActions";
import type { InstanceActions } from "./InstanceActions";
import type { Person } from "./Person";
import type { PersonActions } from "./PersonActions";

/**
 * A slimmer comment view, without the post, or community.
 */
export type CommentSlimView = {
  comment: Comment;
  creator: Person;
  comment_actions?: CommentActions;
  person_actions?: PersonActions;
  creator_community_actions?: CommunityActions;
  instance_communities_actions?: InstanceActions;
  instance_persons_actions?: InstanceActions;
  creator_home_instance_actions?: InstanceActions;
  creator_local_instance_actions?: InstanceActions;
  creator_is_admin: boolean;
  can_mod: boolean;
  creator_banned: boolean;
};
