// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CommentReplyView } from "./CommentReplyView";

/**
 * The response for a comment reply action.
 */
export type CommentReplyResponse = { comment_reply_view: CommentReplyView };
