// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * The community sort types. See here for descriptions: https://join-lemmy.org/docs/en/users/03-votes-and-ranking.html
 */
export type CommunitySortType =
  | "active_six_months"
  | "active_monthly"
  | "active_weekly"
  | "active_daily"
  | "hot"
  | "new"
  | "old"
  | "name_asc"
  | "name_desc"
  | "comments"
  | "posts"
  | "subscribers"
  | "subscribers_local";
