// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Defines who can browse and interact with content in a community.
 */
export type CommunityVisibility = "Public" | "LocalOnly" | "Private";
