// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CommentView } from "./CommentView";
import type { LocalUserId } from "./LocalUserId";

/**
 * A comment response.
 */
export type CommentResponse = {
  comment_view: CommentView;
  recipient_ids: Array<LocalUserId>;
};
