// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CommentId } from "./CommentId";

export interface CommentAggregates {
  id: number;
  comment_id: CommentId;
  score: bigint;
  upvotes: bigint;
  downvotes: bigint;
  published: string;
  child_count: number;
}
