// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Available settings for community notifications
 */
export type CommunityNotificationsMode =
  | "all_posts_and_comments"
  | "all_posts"
  | "replies_and_mentions"
  | "mute";
