// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CommunityId } from "./CommunityId";

export interface CommunityAggregates {
  id: number;
  community_id: CommunityId;
  subscribers: bigint;
  posts: bigint;
  comments: bigint;
  published: string;
  users_active_day: bigint;
  users_active_week: bigint;
  users_active_month: bigint;
  users_active_half_year: bigint;
}
