// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CommentId } from "./CommentId";
import type { CommentReplyId } from "./CommentReplyId";
import type { PersonId } from "./PersonId";

export interface CommentReply {
  id: CommentReplyId;
  recipient_id: PersonId;
  comment_id: CommentId;
  read: boolean;
  published: string;
}
