// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Community } from "./Community";
import type { CommunityActions } from "./CommunityActions";
import type { InstanceActions } from "./InstanceActions";

/**
 * A community view.
 */
export type CommunityView = {
  community: Community;
  community_actions?: CommunityActions;
  instance_actions?: InstanceActions;
  can_mod: boolean;
};
