// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CommunityId } from "./CommunityId";

/**
 * Parameter for setting community icon or banner. Can't use POST data here as it already contains
 * the image data.
 */
export type CommunityIdQuery = { id: CommunityId };
