// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CommentId } from "./CommentId";
import type { PersonId } from "./PersonId";

export type CommentActions = {
  person_id: PersonId;
  comment_id: CommentId;
  /**
   * The like / score for the comment.
   */
  like_score?: number;
  /**
   * When the comment was liked.
   */
  liked?: string;
  /**
   * When the comment was saved.
   */
  saved?: string;
};
