// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CommunityTag } from "./CommunityTag";

/**
 * We wrap this in a struct so we can implement FromSqlRow<Json> for it
 */
export type CommunityTagsView = Array<CommunityTag>;
