// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Comment } from "./Comment";
import type { CommentAggregates } from "./CommentAggregates";
import type { Person } from "./Person";
import type { SubscribedType } from "./SubscribedType";

/**
 * A slimmer comment view, without the post, or community.
 */
export type CommentSlimView = {
  comment: Comment;
  creator: Person;
  counts: CommentAggregates;
  creator_banned_from_community: boolean;
  banned_from_community: boolean;
  creator_is_moderator: boolean;
  creator_is_admin: boolean;
  subscribed: SubscribedType;
  /**
   * The time when the comment was saved.
   */
  saved?: string;
  creator_blocked: boolean;
  my_vote?: number;
  can_mod: boolean;
};
