// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Community } from "./Community";
import type { Person } from "./Person";

export interface CommunityFollowerView {
  community: Community;
  follower: Person;
}
