// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Comment } from "./Comment";
import type { CommentReport } from "./CommentReport";
import type { Community } from "./Community";
import type { Person } from "./Person";
import type { Post } from "./Post";
import type { SubscribedType } from "./SubscribedType";

/**
 * A comment report view.
 */
export type CommentReportView = {
  comment_report: CommentReport;
  comment: Comment;
  post: Post;
  community: Community;
  creator: Person;
  comment_creator: Person;
  creator_banned_from_community: boolean;
  creator_is_moderator: boolean;
  creator_is_admin: boolean;
  creator_blocked: boolean;
  subscribed: SubscribedType;
  /**
   * The time when the comment was saved.
   */
  saved?: string;
  my_vote?: number;
  resolver?: Person;
};
