// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CommunityId } from "./CommunityId";
import type { TagId } from "./TagId";

export type CommunityTagResponse = {
  id: TagId;
  name: string;
  community_id: CommunityId;
};
