// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CommentReportView } from "./CommentReportView";

export interface CommentReportResponse {
  comment_report_view: CommentReportView;
}
