// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type CountsResponse = {
  notification_count: number;
  report_count: number;
  pending_follow_count: number;
  registration_application_count: number;
};
