// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { PersonId } from "./PersonId";

/**
 * Create a private message.
 */
export type CreatePrivateMessage = { content: string; recipient_id: PersonId };
