// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export interface CreateCustomEmoji {
  category: string;
  shortcode: string;
  image_url: string;
  alt_text: string;
  keywords: Array<string>;
  auth: string;
}
