// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CommentId } from "./CommentId";

/**
 * Like a comment.
 */
export type CreateCommentLike = {
  comment_id: CommentId;
  /**
   * Must be -1, 0, or 1 .
   */
  score: number;
};
