// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { PrivateMessageId } from "./PrivateMessageId";

/**
 * Create a report for a private message.
 */
export type CreatePrivateMessageReport = {
  private_message_id: PrivateMessageId;
  reason: string;
};
