// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { PostId } from "./PostId";

/**
 * Like a post.
 */
export type CreatePostLike = {
  post_id: PostId;
  /**
   * True means Upvote, False means Downvote, and None means remove vote.
   */
  is_upvote?: boolean;
};
