// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CommentId } from "./CommentId";

/**
 * Report a comment.
 */
export type CreateCommentReport = {
  comment_id: CommentId;
  reason: string;
  /**
   * The comment violates rules of the local instance. This report will only be shown to local
   * admins, not to community mods and will not be federated.
   */
  violates_instance_rules?: boolean;
};
