// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CommentId } from "./CommentId";

/**
 * Creates a warning against a comment and notifies the user.
 */
export type CreateCommentWarning = { comment_id: CommentId; reason: string };
