// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { DbUrl } from "./DbUrl";

/**
 * Create a custom emoji.
 */
export type CreateCustomEmoji = {
  category: string;
  shortcode: string;
  image_url: DbUrl;
  alt_text: string;
  keywords: Array<string>;
};
