// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { PostId } from "./PostId";

/**
 * Create a post report.
 */
export type CreatePostReport = {
  post_id: PostId;
  reason: string;
  /**
   * The post violates rules of the local instance. This report will only be shown to local
   * admins, not to community mods and will not be federated.
   */
  violates_instance_rules?: boolean;
};
