// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { PostId } from "./PostId";

/**
 * Creates a warning against a post and notifies the user.
 */
export type CreatePostWarning = { post_id: PostId; reason: string };
