// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { PersonId } from "./PersonId";

export interface CreatePrivateMessage {
  content: string;
  recipient_id: PersonId;
  auth: string;
}
