// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { PrivateMessageId } from "./PrivateMessageId";

export interface CreatePrivateMessageReport {
  private_message_id: PrivateMessageId;
  reason: string;
  auth: string;
}
