// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CommunityId } from "./CommunityId";

/**
 * Create a report for a community.
 */
export type CreateCommunityReport = {
  community_id: CommunityId;
  reason: string;
};
