// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CommunityId } from "./CommunityId";
import type { LanguageId } from "./LanguageId";

export interface CreatePost {
  name: string;
  community_id: CommunityId;
  url?: string;
  body?: string;
  honeypot?: string;
  nsfw?: boolean;
  language_id?: LanguageId;
  auth: string;
}
