// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CommunityId } from "./CommunityId";

/**
 * Create a tag for a community.
 */
export type CreateCommunityTag = {
  community_id: CommunityId;
  name: string;
  display_name?: string;
  summary?: string;
};
