// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { LocalUserInvite } from "./LocalUserInvite";

export type CreateInvitationResponse = { invite: LocalUserInvite };
