// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CustomEmojiView } from "./CustomEmojiView";

/**
 * A response for a custom emoji.
 */
export type CustomEmojiResponse = { custom_emoji: CustomEmojiView };
