// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CustomEmoji } from "./CustomEmoji";
import type { CustomEmojiKeyword } from "./CustomEmojiKeyword";

/**
 * A custom emoji view.
 */
export type CustomEmojiView = {
  custom_emoji: CustomEmoji;
  keywords: Array<CustomEmojiKeyword>;
};
