// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { SensitiveString } from "./SensitiveString";

/**
 * Delete your account.
 */
export type DeleteAccount = {
  password: SensitiveString;
  delete_content: boolean;
};
