// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CommunityTagId } from "./CommunityTagId";

/**
 * Delete a community tag.
 */
export type DeleteCommunityTag = { tag_id: CommunityTagId; delete: boolean };
