// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CommunityId } from "./CommunityId";

/**
 * Delete your own community.
 */
export type DeleteCommunity = { community_id: CommunityId; deleted: boolean };
