// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { PersonId } from "./PersonId";

/**
 * Used for delete user plugin hooks
 */
export type DeleteUserForm = { person_id: PersonId; delete_content: boolean };
