// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { PrivateMessageId } from "./PrivateMessageId";

export interface DeletePrivateMessage {
  private_message_id: PrivateMessageId;
  deleted: boolean;
  auth: string;
}
