// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ExternalAuthId } from "./ExternalAuthId";

export interface DeleteExternalAuthResponse {
  id: ExternalAuthId;
  success: boolean;
}
