// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CustomEmojiId } from "./CustomEmojiId";

export interface DeleteCustomEmoji {
  id: CustomEmojiId;
  auth: string;
}
