// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { OAuthProviderId } from "./OAuthProviderId";

/**
 * Delete an external auth method.
 */
export type DeleteOAuthProvider = { id: OAuthProviderId };
