// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CommentId } from "./CommentId";

/**
 * Delete your own comment.
 */
export type DeleteComment = { comment_id: CommentId; deleted: boolean };
