// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { PrivateMessageId } from "./PrivateMessageId";

/**
 * Delete a private message.
 */
export type DeletePrivateMessage = {
  private_message_id: PrivateMessageId;
  deleted: boolean;
};
