// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CommentId } from "./CommentId";

/**
 * Distinguish a comment (IE speak as moderator).
 */
export type DistinguishComment = {
  comment_id: CommentId;
  distinguished: boolean;
};
