// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Make a request to resend your verification email.
 */
export type DonationDialogShown = { hide_permanently?: boolean };
