// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { LanguageId } from "./LanguageId";
import type { PostId } from "./PostId";

export interface EditPost {
  post_id: PostId;
  name?: string;
  url?: string;
  body?: string;
  nsfw?: boolean;
  language_id?: LanguageId;
  auth: string;
}
