// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { PostId } from "./PostId";
import type { PostNotificationsMode } from "./PostNotificationsMode";

/**
 * Change notification settings for a post
 */
export type EditPostNotifications = {
  post_id: PostId;
  mode: PostNotificationsMode;
};
