// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { OAuthProviderId } from "./OAuthProviderId";

export interface EditOAuthProvider {
  id: OAuthProviderId;
  display_name: string | null;
  authorization_endpoint: string | null;
  token_endpoint: string | null;
  userinfo_endpoint: string | null;
  id_claim: string | null;
  client_secret: string | null;
  scopes: string | null;
  auto_verify_email: boolean | null;
  account_linking_enabled: boolean | null;
  enabled: boolean | null;
}
