// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CommentId } from "./CommentId";
import type { LanguageId } from "./LanguageId";

/**
 * Edit a comment.
 */
export type EditComment = {
  comment_id: CommentId;
  content?: string;
  language_id?: LanguageId;
};
