// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CustomEmojiId } from "./CustomEmojiId";
import type { DbUrl } from "./DbUrl";

/**
 * Edit a custom emoji.
 */
export type EditCustomEmoji = {
  id: CustomEmojiId;
  category?: string;
  shortcode?: string;
  image_url?: DbUrl;
  alt_text?: string;
  keywords?: Array<string>;
};
