// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { PrivateMessageId } from "./PrivateMessageId";

/**
 * Edit a private message.
 */
export type EditPrivateMessage = {
  private_message_id: PrivateMessageId;
  content: string;
};
