// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { TagId } from "./TagId";

/**
 * Make changes to a community tag
 */
export type EditCommunityTag = {
  tag_id: TagId;
  display_name?: string;
  description?: string;
};
