// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CommunityTagId } from "./CommunityTagId";
import type { TagColor } from "./TagColor";

/**
 * Make changes to a community tag
 */
export type EditCommunityTag = {
  tag_id: CommunityTagId;
  display_name?: string;
  summary?: string;
  color?: TagColor;
};
