// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ExternalAuthId } from "./ExternalAuthId";
import type { LocalSiteId } from "./LocalSiteId";

export interface ExternalAuth {
  id: ExternalAuthId;
  local_site_id: LocalSiteId;
  display_name: string;
  auth_type: string;
  auth_endpoint: string;
  token_endpoint: string;
  user_endpoint: string;
  id_attribute: string;
  issuer: string;
  client_id: string;
  client_secret: string;
  scopes: string;
  published: string;
  updated: string;
}
