// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ExternalAuthView } from "./ExternalAuthView";

export interface ExternalAuthResponse {
  external_auth: ExternalAuthView;
}
