// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ExternalAuth } from "./ExternalAuth";

export interface ExternalAuthView {
  external_auth: ExternalAuth;
}
