// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { PostFeatureType } from "./PostFeatureType";
import type { PostId } from "./PostId";

/**
 * Feature a post (stickies / pins to the top).
 */
export type FeaturePost = {
  post_id: PostId;
  featured: boolean;
  feature_type: PostFeatureType;
};
