// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { FederationAllowList } from "./FederationAllowList";
import type { FederationBlockList } from "./FederationBlockList";
import type { FederationQueueState } from "./FederationQueueState";
import type { Instance } from "./Instance";
import type { Site } from "./Site";

export type FederatedInstanceView = {
  instance: Instance;
  site?: Site;
  queue_state?: FederationQueueState;
  blocked?: FederationBlockList;
  allowed?: FederationAllowList;
};
