// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Instance } from "./Instance";

export interface FederatedInstances {
  linked: Array<Instance>;
  allowed: Array<Instance>;
  blocked: Array<Instance>;
}
