// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { InstanceWithFederationState } from "./InstanceWithFederationState";

export interface FederatedInstances {
  linked: Array<InstanceWithFederationState>;
  allowed: Array<InstanceWithFederationState>;
  blocked: Array<InstanceWithFederationState>;
}
