// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * The federation mode for an item
 */
export type FederationMode = "All" | "Local" | "Disable";
