// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CommunityId } from "./CommunityId";

/**
 * Follow / subscribe to a community.
 */
export type FollowCommunity = { community_id: CommunityId; follow: boolean };
