// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CommunityId } from "./CommunityId";

/**
 * Get a community. Must provide either an id, or a name.
 */
export type GetCommunity = {
  id?: CommunityId;
  /**
   * Example: star_trek , or star_trek@xyz.tld
   */
  name?: string;
};
