// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CommentSlimView } from "./CommentSlimView";

/**
 * A slimmer comment list response, without the post or community.
 */
export type GetCommentsSlimResponse = { comments: Array<CommentSlimView> };
