// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { NameOrId } from "./NameOrId";

/**
 * Get a community. Must provide either an id, or a name (eg star_trek or star_trek@xyz.tld).
 */
export type GetCommunity = {
  /**
   * Example: `star_trek`, or `star_trek@xyz.tld` or `12`
   */
  name_or_id: NameOrId;
};
