// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CaptchaResponse } from "./CaptchaResponse";

/**
 * A wrapper for the captcha response.
 */
export type GetCaptchaResponse = {
  /**
   * Will be None if captchas are disabled.
   */
  ok?: CaptchaResponse;
};
