// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { GetFederatedInstancesKind } from "./GetFederatedInstancesKind";
import type { PaginationCursor } from "./PaginationCursor";

export type GetFederatedInstances = {
  domain_filter?: string;
  kind: GetFederatedInstancesKind;
  page_cursor?: PaginationCursor;
  page_back?: boolean;
  limit?: number;
};
