// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { FederatedInstances } from "./FederatedInstances";

/**
 * A response of federated instances.
 */
export type GetFederatedInstancesResponse = {
  /**
   * Optional, because federation may be disabled.
   */
  federated_instances?: FederatedInstances;
};
