// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { FederatedInstanceView } from "./FederatedInstanceView";
import type { PaginationCursor } from "./PaginationCursor";

/**
 * A response of federated instances.
 */
export type GetFederatedInstancesResponse = {
  federated_instances: Array<FederatedInstanceView>;
  next_page?: PaginationCursor;
  prev_page?: PaginationCursor;
};
