// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CommentId } from "./CommentId";
import type { CommunityId } from "./CommunityId";
import type { ModlogActionType } from "./ModlogActionType";
import type { PersonId } from "./PersonId";
import type { PostId } from "./PostId";

export interface GetModlog {
  mod_person_id?: PersonId;
  community_id?: CommunityId;
  page?: /* integer */ number;
  limit?: /* integer */ number;
  type_?: ModlogActionType;
  other_person_id?: PersonId;
  post_id?: PostId;
  comment_id?: CommentId;
}
