// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ModlogCombinedView } from "./ModlogCombinedView";

/**
 * The modlog fetch response.
 */
export type GetModlogResponse = { modlog: Array<ModlogCombinedView> };
