// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CommunityView } from "./CommunityView";
import type { MultiCommunity } from "./MultiCommunity";
import type { Person } from "./Person";

export type GetMultiCommunityResponse = {
  communities: Array<CommunityView>;
  multi: MultiCommunity;
  owner: Person;
};
