// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ModlogView } from "./ModlogView";
import type { PaginationCursor } from "./PaginationCursor";

/**
 * The modlog fetch response.
 */
export type GetModlogResponse = {
  modlog: Array<ModlogView>;
  /**
   * the pagination cursor to use to fetch the next page
   */
  next_page?: PaginationCursor;
  prev_page?: PaginationCursor;
};
