// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { MultiCommunityId } from "./MultiCommunityId";

export type GetMultiCommunity = { id?: MultiCommunityId; name?: string };
