// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CommunityView } from "./CommunityView";
import type { PostView } from "./PostView";

/**
 * The post response.
 */
export type GetPostResponse = {
  post_view: PostView;
  community_view: CommunityView;
  /**
   * A list of cross-posts, or other times / communities this link has been posted to.
   */
  cross_posts: Array<PostView>;
};
