// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { PostView } from "./PostView";

export interface GetPostsResponse {
  posts: Array<PostView>;
}
