// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { PostOrCommentId } from "./PostOrCommentId";

export interface GetPost {
  id: PostOrCommentId;
  auth?: string;
}
