// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { PersonMentionView } from "./PersonMentionView";

/**
 * The response of mentions for your user.
 */
export type GetPersonMentionsResponse = { mentions: Array<PersonMentionView> };
