// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CommentSortType } from "./CommentSortType";

/**
 * Get mentions for your user.
 */
export type GetPersonMentions = {
  sort?: CommentSortType;
  page?: number;
  limit?: number;
  unread_only?: boolean;
};
