// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CommunityModeratorView } from "./CommunityModeratorView";
import type { MultiCommunityView } from "./MultiCommunityView";
import type { PersonView } from "./PersonView";
import type { Site } from "./Site";

/**
 * A person's details response.
 */
export type GetPersonDetailsResponse = {
  person_view: PersonView;
  site?: Site;
  moderates: Array<CommunityModeratorView>;
  multi_communities_created: Array<MultiCommunityView>;
};
