// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CommentReplyView } from "./CommentReplyView";

/**
 * Fetches your replies.
 */
export type GetRepliesResponse = { replies: Array<CommentReplyView> };
