// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CommentSortType } from "./CommentSortType";

export interface GetReplies {
  sort?: CommentSortType;
  page?: bigint;
  limit?: bigint;
  unread_only?: boolean;
  auth: string;
}
