// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ListingType } from "./ListingType";

export interface GetRandomCommunity {
  type_?: ListingType;
}
