// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CommunityId } from "./CommunityId";

export interface GetReportCountResponse {
  community_id?: CommunityId;
  comment_reports: bigint;
  post_reports: bigint;
  private_message_reports?: bigint;
}
