// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CommunityId } from "./CommunityId";

/**
 * Get a count of the number of reports.
 */
export type GetReportCount = { community_id?: CommunityId };
