// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CommentSortType } from "./CommentSortType";

export interface GetReplies {
  sort?: CommentSortType;
  page?: /* integer */ number;
  limit?: /* integer */ number;
  unread_only?: boolean;
}
