// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ListingType } from "./ListingType";

/**
 * Fetches a random community
 */
export type GetRandomCommunity = { type_?: ListingType };
