// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { PersonId } from "./PersonId";

/**
 * Gets a registration application for a person
 */
export type GetRegistrationApplication = { person_id: PersonId };
