// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { LinkMetadata } from "./LinkMetadata";

/**
 * The site metadata response.
 */
export type GetSiteMetadataResponse = { metadata: LinkMetadata };
