// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * The count of unread registration applications.
 */
export type GetUnreadRegistrationApplicationCountResponse = {
  registration_applications: bigint;
};
