// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export interface GetUnreadCountResponse {
  replies: /* integer */ number;
  mentions: /* integer */ number;
  private_messages: /* integer */ number;
}
