// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A response containing a count of unread notifications.
 */
export type GetUnreadCountResponse = { count: bigint };
