// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { PostId } from "./PostId";

/**
 * Hide a post from list views
 */
export type HidePost = { post_ids: Array<PostId>; hide: boolean };
