// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { DbUrl } from "./DbUrl";

export type ImageDetails = {
  link: DbUrl;
  width: number;
  height: number;
  content_type: string;
};
