// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type ImageProxyParams = {
  url: string;
  file_type: string | null;
  max_size: number | null;
};
