// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A mode for setting how pictrs handles images.
 */
export type ImageMode = "none" | "store_link_previews" | "proxy_all_images";
