// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export interface ImageDetails {
  link: string;
  width: number;
  height: number;
  content_type: string;
}
