// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CommentReplyId } from "./CommentReplyId";
import type { InboxCombinedId } from "./InboxCombinedId";
import type { PersonCommentMentionId } from "./PersonCommentMentionId";
import type { PersonPostMentionId } from "./PersonPostMentionId";
import type { PrivateMessageId } from "./PrivateMessageId";

/**
 * A combined inbox table.
 */
export type InboxCombined = {
  id: InboxCombinedId;
  published_at: string;
  comment_reply_id?: CommentReplyId;
  person_comment_mention_id?: PersonCommentMentionId;
  person_post_mention_id?: PersonPostMentionId;
  private_message_id?: PrivateMessageId;
};
