// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Instance } from "./Instance";
import type { Person } from "./Person";
import type { Site } from "./Site";

export interface InstanceBlockView {
  person: Person;
  instance: Instance;
  site?: Site;
}
