// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type InstanceActions = {
  /**
   * When the instance's communities were blocked.
   */
  blocked_communities_at?: string;
  /**
   * When this user received a site ban.
   */
  received_ban_at?: string;
  /**
   * When their ban expires.
   */
  ban_expires_at?: string;
  /**
   * When the instance's persons were blocked.
   */
  blocked_persons_at?: string;
};
