// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { InstanceId } from "./InstanceId";

/**
 * A federated instance / site.
 */
export type Instance = {
  id: InstanceId;
  domain: string;
  published: string;
  /**
   * When the instance was updated.
   */
  updated?: string;
  /**
   * The software of the instance.
   */
  software?: string;
  /**
   * The version of the instance's software.
   */
  version?: string;
};
