// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { InstanceId } from "./InstanceId";

/**
 * A federated instance / site.
 */
export type Instance = {
  id: InstanceId;
  domain: string;
  published: string;
  updated?: string;
  software?: string;
  version?: string;
};
