// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type InstanceActions = {
  /**
   * When the instance was blocked.
   */
  blocked?: string;
  /**
   * When this user received a site ban.
   */
  received_ban?: string;
  /**
   * When their ban expires.
   */
  ban_expires?: string;
};
