// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { LanguageId } from "./LanguageId";

export interface Language {
  id: LanguageId;
  code: string;
  name: string;
}
