// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * The like_type for a persons liked content.
 */
export type LikeType = "all" | "liked_only" | "disliked_only";
