// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export interface LinkMetadata {
  title?: string;
  description?: string;
  image?: string;
  embed_video_url?: string;
  content_type?: string;
}
