// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { DbUrl } from "./DbUrl";

/**
 * Site metadata, from its opengraph tags.
 */
export type LinkMetadata = {
  content_type?: string;
  title?: string;
  description?: string;
  image?: DbUrl;
  embed_video_url?: DbUrl;
};
