// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { PaginationCursor } from "./PaginationCursor";
import type { RegistrationApplicationView } from "./RegistrationApplicationView";

/**
 * The list of registration applications.
 */
export type ListRegistrationApplicationsResponse = {
  registration_applications: Array<RegistrationApplicationView>;
  /**
   * the pagination cursor to use to fetch the next page
   */
  next_page?: PaginationCursor;
  prev_page?: PaginationCursor;
};
