// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { MultiCommunityListingType } from "./MultiCommunityListingType";
import type { MultiCommunitySortType } from "./MultiCommunitySortType";
import type { PaginationCursor } from "./PaginationCursor";
import type { PersonId } from "./PersonId";

export type ListMultiCommunities = {
  type_?: MultiCommunityListingType;
  sort?: MultiCommunitySortType;
  creator_id?: PersonId;
  /**
   * Filter to within a given time range, in seconds.
   * IE 60 would give results for the past minute.
   */
  time_range_seconds?: number;
  page_cursor?: PaginationCursor;
  limit?: number;
};
