// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { NotificationView } from "./NotificationView";
import type { PaginationCursor } from "./PaginationCursor";

/**
 * Get your inbox (replies, comment mentions, post mentions, and messages)
 */
export type ListNotificationsResponse = {
  notifications: Array<NotificationView>;
  /**
   * the pagination cursor to use to fetch the next page
   */
  next_page?: PaginationCursor;
  prev_page?: PaginationCursor;
};
