// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Tagline } from "./Tagline";

/**
 * A response for taglines.
 */
export type ListTaglinesResponse = { taglines: Array<Tagline> };
