// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export interface ListCommunityPendingFollows {
  pending_only: boolean | null;
  all_communities: boolean | null;
  page: number | null;
  limit: number | null;
}
