// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CommunityView } from "./CommunityView";

/**
 * The response for listing communities.
 */
export type ListCommunitiesResponse = { communities: Array<CommunityView> };
