// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { PaginationCursor } from "./PaginationCursor";

export type ListCommunityPendingFollows = {
  /**
   * Only shows the unapproved applications
   */
  pending_only?: boolean;
  all_communities?: boolean;
  page_cursor?: PaginationCursor;
  page_back?: boolean;
  limit?: bigint;
};
