// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { PaginationCursor } from "./PaginationCursor";

/**
 * List the banned persons.
 */
export type ListBannedPersons = {
  page_cursor?: PaginationCursor;
  page_back?: boolean;
  limit?: number;
};
