// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CommunityId } from "./CommunityId";

export interface ListCommentReports {
  page?: number;
  limit?: number;
  unresolved_only?: boolean;
  community_id?: CommunityId;
  auth: string;
}
