// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export interface ListPrivateMessageReports {
  page?: bigint;
  limit?: bigint;
  unresolved_only?: boolean;
  auth: string;
}
