// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { PaginationCursor } from "./PaginationCursor";

/**
 * Gets your read posts.
 */
export type ListPersonRead = { page_cursor?: PaginationCursor; limit?: number };
