// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { MultiCommunityView } from "./MultiCommunityView";
import type { PaginationCursor } from "./PaginationCursor";

export type ListMultiCommunitiesResponse = {
  multi_communities: Array<MultiCommunityView>;
  /**
   * the pagination cursor to use to fetch the next page
   */
  next_page?: PaginationCursor;
  prev_page?: PaginationCursor;
};
