// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { PostReportView } from "./PostReportView";

/**
 * The post reports response.
 */
export type ListPostReportsResponse = { post_reports: Array<PostReportView> };
