// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ReportCombinedView } from "./ReportCombinedView";

/**
 * The post reports response.
 */
export type ListReportsResponse = { reports: Array<ReportCombinedView> };
