// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CommentId } from "./CommentId";

export interface ListCommentLikes {
  comment_id: CommentId;
  page?: /* integer */ number;
  limit?: /* integer */ number;
}
