// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { PersonId } from "./PersonId";

export type ListMultiCommunities = {
  creator_id?: PersonId;
  followed_only?: boolean;
};
