// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { PaginationCursor } from "./PaginationCursor";
import type { PersonContentCombinedView } from "./PersonContentCombinedView";

/**
 * A person's content response.
 */
export type ListPersonContentResponse = {
  content: Array<PersonContentCombinedView>;
  /**
   * the pagination cursor to use to fetch the next page
   */
  next_page?: PaginationCursor;
};
