// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export interface ListPrivateMessageReports {
  page?: /* integer */ number;
  limit?: /* integer */ number;
  unresolved_only?: boolean;
}
