// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { InboxCombinedView } from "./InboxCombinedView";

/**
 * Get your inbox (replies, comment mentions, post mentions, and messages)
 */
export type ListInboxResponse = { inbox: Array<InboxCombinedView> };
