// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { VoteView } from "./VoteView";

/**
 * The comment likes response
 */
export type ListCommentLikesResponse = { comment_likes: Array<VoteView> };
