// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { NotificationTypeFilter } from "./NotificationTypeFilter";
import type { PaginationCursor } from "./PaginationCursor";

/**
 * Get your inbox (replies, comment mentions, post mentions, and messages)
 */
export type ListNotifications = {
  type_?: NotificationTypeFilter;
  unread_only?: boolean;
  page_cursor?: PaginationCursor;
  limit?: number;
};
