// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { PaginationCursor } from "./PaginationCursor";

/**
 * Get your user's image / media uploads.
 */
export type ListMedia = {
  page_cursor?: PaginationCursor;
  page_back?: boolean;
  limit?: number;
};
