// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { InboxCombinedPaginationCursor } from "./InboxCombinedPaginationCursor";
import type { InboxDataType } from "./InboxDataType";

/**
 * Get your inbox (replies, comment mentions, post mentions, and messages)
 */
export type ListInbox = {
  type_?: InboxDataType;
  unread_only?: boolean;
  page_cursor?: InboxCombinedPaginationCursor;
  page_back?: boolean;
};
