// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CommentId } from "./CommentId";

/**
 * List comment likes. Admins-only.
 */
export type ListCommentLikes = {
  comment_id: CommentId;
  page?: number;
  limit?: number;
};
