// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type ListCommunityPendingFollows = {
  /**
   * Only shows the unapproved applications
   */
  pending_only?: boolean;
  all_communities?: boolean;
  page?: number;
  limit?: number;
};
