// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { PaginationCursor } from "./PaginationCursor";
import type { PersonListingType } from "./PersonListingType";
import type { PersonSortType } from "./PersonSortType";

export type ListPersons = {
  type_?: PersonListingType;
  sort?: PersonSortType;
  search_term?: string;
  search_title_only?: boolean;
  page_cursor?: PaginationCursor;
  limit?: number;
};
