// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { PendingFollow } from "./PendingFollow";

export type ListCommunityPendingFollowsResponse = {
  items: Array<PendingFollow>;
};
