// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A listing type for post and comment list fetches.
 */
export type ListingType =
  | "all"
  | "local"
  | "subscribed"
  | "moderator_view"
  | "suggested";
