// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { PersonContentCombinedView } from "./PersonContentCombinedView";

/**
 * A person's saved content response.
 */
export type ListPersonSavedResponse = {
  saved: Array<PersonContentCombinedView>;
};
