// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * List private message reports.
 */
export type ListPrivateMessageReports = {
  page?: number;
  limit?: number;
  /**
   * Only shows the unresolved reports
   */
  unresolved_only?: boolean;
};
