// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CommentId } from "./CommentId";
import type { CommunityId } from "./CommunityId";

/**
 * List comment reports.
 */
export type ListCommentReports = {
  comment_id?: CommentId;
  page?: number;
  limit?: number;
  /**
   * Only shows the unresolved reports
   */
  unresolved_only?: boolean;
  /**
   * if no community is given, it returns reports for all communities moderated by the auth user
   */
  community_id?: CommunityId;
};
