// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CommentId } from "./CommentId";
import type { CommunityId } from "./CommunityId";

export interface ListCommentReports {
  comment_id?: CommentId;
  page?: /* integer */ number;
  limit?: /* integer */ number;
  unresolved_only?: boolean;
  community_id?: CommunityId;
}
