// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CustomEmojiView } from "./CustomEmojiView";

export interface ListCustomEmojisResponse {
  custom_emojis: Array<CustomEmojiView>;
}
