// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { RegistrationApplicationView } from "./RegistrationApplicationView";

export interface ListRegistrationApplicationsResponse {
  registration_applications: Array<RegistrationApplicationView>;
}
