// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export interface ListCustomEmojis {
  page?: number;
  limit?: number;
  category?: string;
  ignore_page_limits?: boolean;
}
