// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Fetches a list of custom emojis.
 */
export type ListCustomEmojis = { category?: string };
