// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { MultiCommunity } from "./MultiCommunity";

export type ListMultiCommunitiesResponse = {
  multi_communities: Array<MultiCommunity>;
};
