// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { VoteView } from "./VoteView";

export interface ListPostLikesResponse {
  post_likes: Array<VoteView>;
}
