// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { NameOrId } from "./NameOrId";
import type { PaginationCursor } from "./PaginationCursor";
import type { PersonContentType } from "./PersonContentType";

/**
 * Gets a person's content (posts and comments)
 */
export type ListPersonContent = {
  type_?: PersonContentType;
  /**
   * Example: `dessalines`, or `dessalines@xyz.tld`, or `12`
   */
  person_name_or_id: NameOrId;
  page_cursor?: PaginationCursor;
  page_back?: boolean;
  limit?: number;
};
