// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CommunitySortType } from "./CommunitySortType";
import type { ListingType } from "./ListingType";
import type { MultiCommunityId } from "./MultiCommunityId";
import type { PaginationCursor } from "./PaginationCursor";

/**
 * Fetches a list of communities.
 */
export type ListCommunities = {
  type_?: ListingType;
  sort?: CommunitySortType;
  /**
   * Filter to within a given time range, in seconds.
   * IE 60 would give results for the past minute.
   */
  time_range_seconds?: number;
  show_nsfw?: boolean;
  multi_community_id?: MultiCommunityId;
  search_term?: string;
  search_title_only?: boolean;
  page_cursor?: PaginationCursor;
  limit?: number;
};
