// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { LocalImage } from "./LocalImage";
import type { Person } from "./Person";

export interface LocalImageView {
  local_image: LocalImage;
  person: Person;
}
