// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { LocalUserId } from "./LocalUserId";

export interface LocalUserVoteDisplayMode {
  local_user_id: LocalUserId;
  score: boolean;
  upvotes: boolean;
  downvotes: boolean;
  upvote_percentage: boolean;
}
