// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { PersonId } from "./PersonId";
import type { PostId } from "./PostId";

export type LocalImage = {
  pictrs_alias: string;
  published_at: string;
  person_id: PersonId;
  /**
   * This means the image is an auto-generated thumbnail, for a post.
   */
  thumbnail_for_post_id?: PostId;
};
