// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { LocalImage } from "./LocalImage";
import type { Person } from "./Person";
import type { Post } from "./Post";

/**
 * A local image view.
 */
export type LocalImageView = {
  local_image: LocalImage;
  person: Person;
  post?: Post;
};
