// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { LocalUser } from "./LocalUser";
import type { LocalUserVoteDisplayMode } from "./LocalUserVoteDisplayMode";
import type { Person } from "./Person";

/**
 * A local user view.
 */
export type LocalUserView = {
  local_user: LocalUser;
  local_user_vote_display_mode: LocalUserVoteDisplayMode;
  person: Person;
};
