// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { InvitationId } from "./InvitationId";
import type { LocalUserId } from "./LocalUserId";

export type LocalUserInvite = {
  id: InvitationId;
  token: string;
  local_user_id: LocalUserId;
  max_uses?: number;
  uses_count: number;
  expires_at?: string;
  published_at: string;
};
