// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export interface LocalUserVoteDisplayMode {
  score: boolean;
  upvotes: boolean;
  downvotes: boolean;
  upvote_percentage: boolean;
}
