// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * The vote display settings for your user.
 */
export type LocalUserVoteDisplayMode = {
  score: boolean;
  upvotes: boolean;
  downvotes: boolean;
  upvote_percentage: boolean;
};
