// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type LocalSiteUrlBlocklist = {
  id: number;
  url: string;
  published_at: string;
  updated_at?: string;
};
