// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { PersonId } from "./PersonId";
import type { PostId } from "./PostId";

export type LocalImage = {
  pictrs_alias: string;
  published: string;
  person_id: PersonId;
  thumbnail_and_post_id?: PostId;
};
