// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { LocalUserId } from "./LocalUserId";

export type LocalImage = {
  local_user_id?: LocalUserId;
  pictrs_alias: string;
  published: string;
};
