// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CommentId } from "./CommentId";

export type LockComment = {
  comment_id: CommentId;
  locked: boolean;
  reason?: string;
};
