// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CommentId } from "./CommentId";

/**
 * Locks a comment and its children, IE prevents new replies.
 */
export type LockComment = {
  comment_id: CommentId;
  locked: boolean;
  reason?: string;
};
