// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { PostId } from "./PostId";

export interface LockPost {
  post_id: PostId;
  locked: boolean;
  auth: string;
}
