// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export interface LoginResponse {
  jwt?: string;
  registration_created: boolean;
  verify_email_sent: boolean;
}
