// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export interface Login {
  username_or_email: string;
  password: string;
  totp_2fa_token?: string;
}
