// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { LocalUserId } from "./LocalUserId";

export interface LoginToken {
  id: number;
  user_id: LocalUserId;
  published: string;
  ip?: string;
  user_agent?: string;
}
