// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { PersonMentionId } from "./PersonMentionId";

export interface MarkPersonMentionAsRead {
  person_mention_id: PersonMentionId;
  read: boolean;
  auth: string;
}
