// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { PostId } from "./PostId";

/**
 * Mark several posts as read.
 */
export type MarkManyPostsAsRead = { post_ids: Array<PostId> };
