// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { PersonCommentMentionId } from "./PersonCommentMentionId";

/**
 * Mark a person mention as read.
 */
export type MarkPersonCommentMentionAsRead = {
  person_comment_mention_id: PersonCommentMentionId;
  read: boolean;
};
