// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { PersonMentionId } from "./PersonMentionId";

/**
 * Mark a person mention as read.
 */
export type MarkPersonMentionAsRead = {
  person_mention_id: PersonMentionId;
  read: boolean;
};
