// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CommentReplyId } from "./CommentReplyId";

export interface MarkCommentReplyAsRead {
  comment_reply_id: CommentReplyId;
  read: boolean;
  auth: string;
}
