// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { NotificationId } from "./NotificationId";

/**
 * Mark a comment reply as read.
 */
export type MarkNotificationAsRead = {
  notification_id: NotificationId;
  read: boolean;
};
