// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { PostId } from "./PostId";

/**
 * Mark a post as read.
 */
export type MarkPostAsRead = { post_id: PostId; read: boolean };
