// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CommentReplyId } from "./CommentReplyId";

/**
 * Mark a comment reply as read.
 */
export type MarkCommentReplyAsRead = {
  comment_reply_id: CommentReplyId;
  read: boolean;
};
