// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ModAdd } from "./ModAdd";
import type { Person } from "./Person";

export interface ModAddView {
  mod_add: ModAdd;
  moderator?: Person;
  modded_person: Person;
}
