// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Community } from "./Community";
import type { ModAddToCommunity } from "./ModAddToCommunity";
import type { Person } from "./Person";

/**
 * When someone is added as a community moderator.
 */
export type ModAddToCommunityView = {
  mod_add_to_community: ModAddToCommunity;
  moderator?: Person;
  community: Community;
  other_person: Person;
};
