// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ModBan } from "./ModBan";
import type { Person } from "./Person";

/**
 * When someone is banned from the site.
 */
export type ModBanView = {
  mod_ban: ModBan;
  moderator?: Person;
  other_person: Person;
};
