// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ModBanId } from "./ModBanId";
import type { PersonId } from "./PersonId";

/**
 * When someone is banned from the site.
 */
export type ModBan = {
  id: ModBanId;
  mod_person_id: PersonId;
  other_person_id: PersonId;
  reason?: string;
  banned: boolean;
  expires?: string;
  when_: string;
};
