// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CommunityId } from "./CommunityId";
import type { CommunityVisibility } from "./CommunityVisibility";
import type { ModChangeCommunityVisibilityId } from "./ModChangeCommunityVisibilityId";
import type { PersonId } from "./PersonId";

export type ModChangeCommunityVisibility = {
  id: ModChangeCommunityVisibilityId;
  community_id: CommunityId;
  mod_person_id: PersonId;
  published: string;
  visibility: CommunityVisibility;
};
