// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CommunityTagId } from "./CommunityTagId";
import type { PostId } from "./PostId";

/**
 * Mods can change some metadata for posts
 */
export type ModEditPost = {
  post_id: PostId;
  nsfw?: boolean;
  tags?: Array<CommunityTagId>;
};
