// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { PersonId } from "./PersonId";
import type { PostId } from "./PostId";

/**
 * When a moderator features a post on a community (pins it to the top).
 */
export type ModFeaturePost = {
  id: number;
  mod_person_id: PersonId;
  post_id: PostId;
  featured: boolean;
  when_: string;
  is_featured_community: boolean;
};
