// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Community } from "./Community";
import type { ModFeaturePost } from "./ModFeaturePost";
import type { Person } from "./Person";
import type { Post } from "./Post";

/**
 * When a moderator features a post on a community (pins it to the top).
 */
export type ModFeaturePostView = {
  mod_feature_post: ModFeaturePost;
  moderator?: Person;
  modded_person: Person;
  post: Post;
  community: Community;
};
