// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CommunityId } from "./CommunityId";
import type { ModHideCommunityId } from "./ModHideCommunityId";
import type { PersonId } from "./PersonId";

/**
 * When a community is hidden from public view.
 */
export type ModHideCommunity = {
  id: ModHideCommunityId;
  community_id: CommunityId;
  mod_person_id: PersonId;
  published: string;
  reason?: string;
  hidden: boolean;
};
