// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Comment } from "./Comment";
import type { Community } from "./Community";
import type { Instance } from "./Instance";
import type { Modlog } from "./Modlog";
import type { Person } from "./Person";
import type { Post } from "./Post";

export type ModlogView = {
  modlog: Modlog;
  moderator: Person | null;
  target_person: Person | null;
  target_instance: Instance | null;
  target_community: Community | null;
  target_post: Post | null;
  target_comment: Comment | null;
};
