// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ModlogId } from "./ModlogId";
import type { ModlogKind } from "./ModlogKind";

export type Modlog = {
  id: ModlogId;
  kind: ModlogKind;
  is_revert: boolean;
  reason?: string;
  expires_at?: string;
  published_at: string;
};
