// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CommentId } from "./CommentId";
import type { ModLockCommentId } from "./ModLockCommentId";
import type { PersonId } from "./PersonId";

/**
 * When a moderator locks a comment (prevents new replies to a comment or its children).
 */
export type ModLockComment = {
  id: ModLockCommentId;
  mod_person_id: PersonId;
  comment_id: CommentId;
  locked: boolean;
  reason: string;
  published_at: string;
};
