// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CommentId } from "./CommentId";
import type { CommunityId } from "./CommunityId";
import type { PersonId } from "./PersonId";
import type { PostId } from "./PostId";

export interface ModlogListParams {
  community_id?: CommunityId;
  mod_person_id?: PersonId;
  other_person_id?: PersonId;
  post_id?: PostId;
  comment_id?: CommentId;
  page?: number;
  limit?: number;
  hide_modlog_names: boolean;
}
