// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type ModlogActionType =
  | "All"
  | "ModRemovePost"
  | "ModLockPost"
  | "ModFeaturePost"
  | "ModRemoveComment"
  | "ModRemoveCommunity"
  | "ModBanFromCommunity"
  | "ModAddCommunity"
  | "ModTransferCommunity"
  | "ModAdd"
  | "ModBan"
  | "ModHideCommunity"
  | "AdminPurgePerson"
  | "AdminPurgeCommunity"
  | "AdminPurgePost"
  | "AdminPurgeComment";
