// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Comment } from "./Comment";
import type { Community } from "./Community";
import type { Instance } from "./Instance";
import type { Modlog } from "./Modlog";
import type { Person } from "./Person";
import type { Post } from "./Post";

export type ModlogView = {
  modlog: Modlog;
  moderator?: Person;
  target_person?: Person;
  target_instance?: Instance;
  target_community?: Community;
  target_post?: Post;
  target_comment?: Comment;
};
