// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AdminAddView } from "./AdminAddView";
import type { AdminAllowInstanceView } from "./AdminAllowInstanceView";
import type { AdminBanView } from "./AdminBanView";
import type { AdminBlockInstanceView } from "./AdminBlockInstanceView";
import type { AdminPurgeCommentView } from "./AdminPurgeCommentView";
import type { AdminPurgeCommunityView } from "./AdminPurgeCommunityView";
import type { AdminPurgePersonView } from "./AdminPurgePersonView";
import type { AdminPurgePostView } from "./AdminPurgePostView";
import type { AdminRemoveCommunityView } from "./AdminRemoveCommunityView";
import type { ModAddToCommunityView } from "./ModAddToCommunityView";
import type { ModBanFromCommunityView } from "./ModBanFromCommunityView";
import type { ModChangeCommunityVisibilityView } from "./ModChangeCommunityVisibilityView";
import type { ModFeaturePostView } from "./ModFeaturePostView";
import type { ModLockCommentView } from "./ModLockCommentView";
import type { ModLockPostView } from "./ModLockPostView";
import type { ModRemoveCommentView } from "./ModRemoveCommentView";
import type { ModRemovePostView } from "./ModRemovePostView";
import type { ModTransferCommunityView } from "./ModTransferCommunityView";

export type ModlogCombinedView =
  | ({ type_: "AdminAllowInstance" } & AdminAllowInstanceView)
  | ({ type_: "AdminBlockInstance" } & AdminBlockInstanceView)
  | ({ type_: "AdminPurgeComment" } & AdminPurgeCommentView)
  | ({ type_: "AdminPurgeCommunity" } & AdminPurgeCommunityView)
  | ({ type_: "AdminPurgePerson" } & AdminPurgePersonView)
  | ({ type_: "AdminPurgePost" } & AdminPurgePostView)
  | ({ type_: "AdminAdd" } & AdminAddView)
  | ({ type_: "ModAddToCommunity" } & ModAddToCommunityView)
  | ({ type_: "AdminBan" } & AdminBanView)
  | ({ type_: "ModBanFromCommunity" } & ModBanFromCommunityView)
  | ({ type_: "ModFeaturePost" } & ModFeaturePostView)
  | ({
      type_: "ModChangeCommunityVisibility";
    } & ModChangeCommunityVisibilityView)
  | ({ type_: "ModLockPost" } & ModLockPostView)
  | ({ type_: "ModRemoveComment" } & ModRemoveCommentView)
  | ({ type_: "AdminRemoveCommunity" } & AdminRemoveCommunityView)
  | ({ type_: "ModRemovePost" } & ModRemovePostView)
  | ({ type_: "ModTransferCommunity" } & ModTransferCommunityView)
  | ({ type_: "ModLockComment" } & ModLockCommentView);
