// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AdminAddView } from "./AdminAddView";
import type { AdminAllowInstanceView } from "./AdminAllowInstanceView";
import type { AdminBanView } from "./AdminBanView";
import type { AdminBlockInstanceView } from "./AdminBlockInstanceView";
import type { AdminPurgeCommentView } from "./AdminPurgeCommentView";
import type { AdminPurgeCommunityView } from "./AdminPurgeCommunityView";
import type { AdminPurgePersonView } from "./AdminPurgePersonView";
import type { AdminPurgePostView } from "./AdminPurgePostView";
import type { AdminRemoveCommunityView } from "./AdminRemoveCommunityView";
import type { ModAddToCommunityView } from "./ModAddToCommunityView";
import type { ModBanFromCommunityView } from "./ModBanFromCommunityView";
import type { ModChangeCommunityVisibilityView } from "./ModChangeCommunityVisibilityView";
import type { ModFeaturePostView } from "./ModFeaturePostView";
import type { ModLockCommentView } from "./ModLockCommentView";
import type { ModLockPostView } from "./ModLockPostView";
import type { ModRemoveCommentView } from "./ModRemoveCommentView";
import type { ModRemovePostView } from "./ModRemovePostView";
import type { ModTransferCommunityView } from "./ModTransferCommunityView";

export type ModlogCombinedView =
  | ({ type_: "admin_allow_instance" } & AdminAllowInstanceView)
  | ({ type_: "admin_block_instance" } & AdminBlockInstanceView)
  | ({ type_: "admin_purge_comment" } & AdminPurgeCommentView)
  | ({ type_: "admin_purge_community" } & AdminPurgeCommunityView)
  | ({ type_: "admin_purge_person" } & AdminPurgePersonView)
  | ({ type_: "admin_purge_post" } & AdminPurgePostView)
  | ({ type_: "admin_add" } & AdminAddView)
  | ({ type_: "mod_add_to_community" } & ModAddToCommunityView)
  | ({ type_: "admin_ban" } & AdminBanView)
  | ({ type_: "mod_ban_from_community" } & ModBanFromCommunityView)
  | ({ type_: "mod_feature_post" } & ModFeaturePostView)
  | ({
      type_: "mod_change_community_visibility";
    } & ModChangeCommunityVisibilityView)
  | ({ type_: "mod_lock_post" } & ModLockPostView)
  | ({ type_: "mod_remove_comment" } & ModRemoveCommentView)
  | ({ type_: "admin_remove_community" } & AdminRemoveCommunityView)
  | ({ type_: "mod_remove_post" } & ModRemovePostView)
  | ({ type_: "mod_transfer_community" } & ModTransferCommunityView)
  | ({ type_: "mod_lock_comment" } & ModLockCommentView);
