// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Comment } from "./Comment";
import type { Community } from "./Community";
import type { ModLockComment } from "./ModLockComment";
import type { Person } from "./Person";

/**
 * When a moderator locks a comment (prevents replies to it or its children).
 */
export type ModLockCommentView = {
  mod_lock_comment: ModLockComment;
  moderator?: Person;
  other_person: Person;
  comment: Comment;
  community: Community;
};
