// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ModLockPostId } from "./ModLockPostId";
import type { PersonId } from "./PersonId";
import type { PostId } from "./PostId";

/**
 * When a moderator locks a comment (prevents new replies to a comment or its children).
 */
export type ModLockComment = {
  id: ModLockPostId;
  mod_person_id: PersonId;
  comment_id: PostId;
  locked: boolean;
  reason?: string;
  published_at: string;
};
