// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CommunityId } from "./CommunityId";
import type { ModRemoveCommunityId } from "./ModRemoveCommunityId";
import type { PersonId } from "./PersonId";

/**
 * When a moderator removes a community.
 */
export type ModRemoveCommunity = {
  id: ModRemoveCommunityId;
  mod_person_id: PersonId;
  community_id: CommunityId;
  reason?: string;
  removed: boolean;
  published_at: string;
};
