// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Community } from "./Community";
import type { ModRemovePost } from "./ModRemovePost";
import type { Person } from "./Person";
import type { Post } from "./Post";

export interface ModRemovePostView {
  mod_remove_post: ModRemovePost;
  moderator?: Person;
  post: Post;
  community: Community;
}
