// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Comment } from "./Comment";
import type { Community } from "./Community";
import type { ModRemoveComment } from "./ModRemoveComment";
import type { Person } from "./Person";
import type { Post } from "./Post";

/**
 * When a moderator removes a comment.
 */
export type ModRemoveCommentView = {
  mod_remove_comment: ModRemoveComment;
  moderator?: Person;
  modded_person: Person;
  comment: Comment;
  post: Post;
  community: Community;
};
