// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Community } from "./Community";
import type { ModRemoveCommunity } from "./ModRemoveCommunity";
import type { Person } from "./Person";

export interface ModRemoveCommunityView {
  mod_remove_community: ModRemoveCommunity;
  moderator?: Person;
  community: Community;
}
