// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Community } from "./Community";
import type { ModRemovePost } from "./ModRemovePost";
import type { Person } from "./Person";
import type { Post } from "./Post";

/**
 * When a moderator removes a post.
 */
export type ModRemovePostView = {
  mod_remove_post: ModRemovePost;
  moderator?: Person;
  modded_person: Person;
  post: Post;
  community: Community;
};
