// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Community } from "./Community";
import type { ModTransferCommunity } from "./ModTransferCommunity";
import type { Person } from "./Person";

/**
 * When a moderator transfers a community to a new owner.
 */
export type ModTransferCommunityView = {
  mod_transfer_community: ModTransferCommunity;
  moderator?: Person;
  community: Community;
  other_person: Person;
};
