// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type MultiCommunitySortType =
  | "new"
  | "old"
  | "name_asc"
  | "name_desc"
  | "communities"
  | "subscribers"
  | "subscribers_local";
