// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CommunityFollowerState } from "./CommunityFollowerState";
import type { MultiCommunityId } from "./MultiCommunityId";
import type { PersonId } from "./PersonId";

export type MultiCommunityFollow = {
  multi_community_id: MultiCommunityId;
  person_id: PersonId;
  follow_state: CommunityFollowerState;
};
