// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { DbUrl } from "./DbUrl";
import type { InstanceId } from "./InstanceId";
import type { MultiCommunityId } from "./MultiCommunityId";
import type { PersonId } from "./PersonId";

export type MultiCommunity = {
  id: MultiCommunityId;
  creator_id: PersonId;
  instance_id: InstanceId;
  name: string;
  title?: string;
  summary?: string;
  local: boolean;
  deleted: boolean;
  ap_id: DbUrl;
  published_at: string;
  updated_at?: string;
  subscribers: number;
  subscribers_local: number;
  communities: number;
};
