// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { MultiCommunityView } from "./MultiCommunityView";

export type MultiCommunityResponse = {
  multi_community_view: MultiCommunityView;
};
