// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { DbUrl } from "./DbUrl";
import type { MultiCommunityId } from "./MultiCommunityId";
import type { PersonId } from "./PersonId";

export type MultiCommunity = {
  id: MultiCommunityId;
  owner_id: PersonId;
  name: string;
  ap_id: DbUrl;
};
