// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Takes either a name or a numeric ID. For example `main`, `main@lemmy.ml` or `12`.
 */
export type NameOrId = { Name: string } | { Id: number };
