// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { NodeInfoServices } from "./NodeInfoServices";
import type { NodeInfoSoftware } from "./NodeInfoSoftware";
import type { NodeInfoUsage } from "./NodeInfoUsage";

/**
 * Nodeinfo spec: http://nodeinfo.diaspora.software/docson/index.html#/ns/schema/2.1
 */
export type NodeInfo = {
  version?: string;
  software?: NodeInfoSoftware;
  protocols?: Array<string>;
  usage?: NodeInfoUsage;
  openRegistrations?: boolean;
  /**
   * These fields are required by the spec for no reason
   */
  services?: NodeInfoServices;
  metadata?: { [key in string]: string };
};
