// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { NodeInfoUsers } from "./NodeInfoUsers";

export type NodeInfoUsage = {
  users?: NodeInfoUsers;
  localPosts?: number;
  localComments?: number;
};
