// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { PersonId } from "./PersonId";

/**
 * Make a note for a person.
 *
 * An empty string deletes the note.
 */
export type NotePerson = { person_id: PersonId; note: string };
