// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AdminAddId } from "./AdminAddId";
import type { AdminBanId } from "./AdminBanId";
import type { AdminRemoveCommunityId } from "./AdminRemoveCommunityId";
import type { CommentId } from "./CommentId";
import type { ModAddToCommunityId } from "./ModAddToCommunityId";
import type { ModBanFromCommunityId } from "./ModBanFromCommunityId";
import type { ModLockCommentId } from "./ModLockCommentId";
import type { ModLockPostId } from "./ModLockPostId";
import type { ModRemoveCommentId } from "./ModRemoveCommentId";
import type { ModRemovePostId } from "./ModRemovePostId";
import type { ModTransferCommunityId } from "./ModTransferCommunityId";
import type { NotificationId } from "./NotificationId";
import type { NotificationType } from "./NotificationType";
import type { PersonId } from "./PersonId";
import type { PostId } from "./PostId";
import type { PrivateMessageId } from "./PrivateMessageId";

export type Notification = {
  id: NotificationId;
  recipient_id: PersonId;
  comment_id?: CommentId;
  read: boolean;
  published_at: string;
  kind: NotificationType;
  post_id?: PostId;
  private_message_id?: PrivateMessageId;
  admin_add_id?: AdminAddId;
  mod_add_to_community_id?: ModAddToCommunityId;
  admin_ban_id?: AdminBanId;
  mod_ban_from_community_id?: ModBanFromCommunityId;
  mod_lock_post_id?: ModLockPostId;
  mod_remove_comment_id?: ModRemoveCommentId;
  admin_remove_community_id?: AdminRemoveCommunityId;
  mod_remove_post_id?: ModRemovePostId;
  mod_lock_comment_id?: ModLockCommentId;
  mod_transfer_community_id?: ModTransferCommunityId;
};
