// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Comment } from "./Comment";
import type { CommentActions } from "./CommentActions";
import type { Community } from "./Community";
import type { CommunityActions } from "./CommunityActions";
import type { ImageDetails } from "./ImageDetails";
import type { InstanceActions } from "./InstanceActions";
import type { Notification } from "./Notification";
import type { Person } from "./Person";
import type { PersonActions } from "./PersonActions";
import type { PersonNotification } from "./PersonNotification";
import type { Post } from "./Post";
import type { PostActions } from "./PostActions";
import type { PrivateMessage } from "./PrivateMessage";
import type { TagsView } from "./TagsView";

export type NotificationView = {
  notification: Notification;
  person_notification: PersonNotification;
  private_message?: PrivateMessage;
  comment?: Comment;
  post?: Post;
  community?: Community;
  creator: Person;
  recipient: Person;
  image_details?: ImageDetails;
  community_actions?: CommunityActions;
  instance_actions?: InstanceActions;
  post_actions?: PostActions;
  person_actions?: PersonActions;
  comment_actions?: CommentActions;
  item_creator_is_admin: boolean;
  post_tags: TagsView;
  can_mod: boolean;
  creator_banned: boolean;
  creator_is_moderator: boolean;
  creator_banned_from_community: boolean;
};
