// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CommentView } from "./CommentView";
import type { PostView } from "./PostView";
import type { PrivateMessageView } from "./PrivateMessageView";

export type NotificationData =
  | ({ type_: "Comment" } & CommentView)
  | ({ type_: "Post" } & PostView)
  | ({ type_: "PrivateMessage" } & PrivateMessageView);
