// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { NotificationType } from "./NotificationType";

/**
 * A list of possible types for the inbox.
 */
export type NotificationTypeFilter = "all" | NotificationType;
