// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { NotificationData } from "./NotificationData";
import type { NotificationId } from "./NotificationId";
import type { NotificationTypes } from "./NotificationTypes";
import type { PersonId } from "./PersonId";

export type NotificationView = {
  id: NotificationId;
  kind: NotificationTypes;
  recipient_id: PersonId;
  data: NotificationData;
};
