// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AdminAdd } from "./AdminAdd";
import type { AdminBan } from "./AdminBan";
import type { AdminRemoveCommunity } from "./AdminRemoveCommunity";
import type { CommentView } from "./CommentView";
import type { ModAddToCommunity } from "./ModAddToCommunity";
import type { ModBanFromCommunity } from "./ModBanFromCommunity";
import type { ModLockComment } from "./ModLockComment";
import type { ModLockPost } from "./ModLockPost";
import type { ModRemoveComment } from "./ModRemoveComment";
import type { ModRemovePost } from "./ModRemovePost";
import type { ModTransferCommunity } from "./ModTransferCommunity";
import type { PostView } from "./PostView";
import type { PrivateMessageView } from "./PrivateMessageView";

export type NotificationData =
  | ({ type_: "comment" } & CommentView)
  | ({ type_: "post" } & PostView)
  | ({ type_: "private_message" } & PrivateMessageView)
  | ({ type_: "admin_add" } & AdminAdd)
  | ({ type_: "mod_add_to_community" } & ModAddToCommunity)
  | ({ type_: "admin_ban" } & AdminBan)
  | ({ type_: "mod_ban_from_community" } & ModBanFromCommunity)
  | ({ type_: "mod_lock_post" } & ModLockPost)
  | ({ type_: "mod_lock_comment" } & ModLockComment)
  | ({ type_: "mod_remove_post" } & ModRemovePost)
  | ({ type_: "mod_remove_comment" } & ModRemoveComment)
  | ({ type_: "admin_remove_community" } & AdminRemoveCommunity)
  | ({ type_: "mod_transfer_community" } & ModTransferCommunity);
