// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Types of notifications which can be received in inbox
 */
export type NotificationType =
  | "mention"
  | "reply"
  | "subscribed"
  | "private_message"
  | "mod_action";
