// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CommentId } from "./CommentId";
import type { NotificationId } from "./NotificationId";
import type { NotificationTypes } from "./NotificationTypes";
import type { PersonId } from "./PersonId";
import type { PostId } from "./PostId";
import type { PrivateMessageId } from "./PrivateMessageId";

export type Notification = {
  id: NotificationId;
  recipient_id: PersonId;
  comment_id?: CommentId;
  read: boolean;
  published_at: string;
  kind: NotificationTypes;
  post_id?: PostId;
  private_message_id?: PrivateMessageId;
};
