// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Comment } from "./Comment";
import type { Community } from "./Community";
import type { Post } from "./Post";
import type { PrivateMessage } from "./PrivateMessage";

export type NotificationData =
  | { type_: "Post"; post: Post; community: Community }
  | { type_: "Comment"; comment: Comment; post: Post; community: Community }
  | { type_: "PrivateMessage"; pm: PrivateMessage };
