// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Notification } from "./Notification";
import type { NotificationData } from "./NotificationData";

export type NotificationView = {
  notification: Notification;
  data: NotificationData;
};
