// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CommentId } from "./CommentId";
import type { NotificationId } from "./NotificationId";
import type { PostId } from "./PostId";
import type { PrivateMessageId } from "./PrivateMessageId";

/**
 * A person mention.
 */
export type Notification = {
  id: NotificationId;
  post_id?: PostId;
  comment_id?: CommentId;
  private_message_id?: PrivateMessageId;
  published_at: string;
};
