// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export interface OAuthProviderUpdateForm {
  display_name: string | null;
  authorization_endpoint: string;
  token_endpoint: string;
  userinfo_endpoint: string;
  id_claim: string | null;
  name_claim: string | null;
  client_secret: string | null;
  scopes: string | null;
  auto_verify_email: boolean | null;
  auto_approve_application: boolean | null;
  account_linking_enabled: boolean | null;
  enabled: boolean | null;
  updated: string;
}
