// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { LocalUserId } from "./LocalUserId";
import type { OAuthProviderId } from "./OAuthProviderId";

export interface OAuthAccount {
  local_user_id: LocalUserId;
  oauth_provider_id: OAuthProviderId;
  oauth_user_id: string;
  published: string;
  updated?: string;
}
