// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { DbUrl } from "./DbUrl";

/**
 * Site metadata, from its opengraph tags.
 */
export type OpenGraphData = {
  title?: string;
  description?: string;
  image?: DbUrl;
  image_width?: number;
  image_height?: number;
  embed_video_url?: DbUrl;
  video_width?: number;
  video_height?: number;
};
