// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * To get the next or previous page, pass this string unchanged as `page_cursor` in a new request
 * to the same endpoint.
 *
 * Do not attempt to parse or modify the cursor string. The format is internal and may change in
 * minor Lemmy versions.
 */
export type PaginationCursor = string;
