// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * currently this is just a wrapper around post id, but should be seen as opaque from the client's
 * perspective. stringified since we might want to use arbitrary info later, with a P prepended to
 * prevent ossification (api users love to make assumptions (e.g. parse stuff that looks like
 * numbers as numbers) about apis that aren't part of the spec
 */
export type PaginationCursor = string;
