// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export interface PasswordChangeAfterReset {
  token: string;
  password: string;
  password_verify: string;
}
