// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { SensitiveString } from "./SensitiveString";

/**
 * Change your password after receiving a reset request.
 */
export type PasswordChangeAfterReset = {
  token: SensitiveString;
  password: SensitiveString;
  password_verify: SensitiveString;
};
