// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Person } from "./Person";

export interface PendingFollow {
  person: Person;
  is_new_instance: boolean;
}
