// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Community } from "./Community";
import type { Person } from "./Person";
import type { SubscribedType } from "./SubscribedType";

export interface PendingFollow {
  person: Person;
  community: Community;
  is_new_instance: boolean;
  subscribed: SubscribedType;
}
