// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Community } from "./Community";
import type { CommunityFollowerState } from "./CommunityFollowerState";
import type { Person } from "./Person";

export type PendingFollow = {
  person: Person;
  community: Community;
  is_new_instance: boolean;
  follow_state?: CommunityFollowerState;
};
