// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { PersonId } from "./PersonId";
import type { PersonPostMentionId } from "./PersonPostMentionId";
import type { PostId } from "./PostId";

/**
 * A person mention.
 */
export type PersonPostMention = {
  id: PersonPostMentionId;
  recipient_id: PersonId;
  post_id: PostId;
  read: boolean;
  published: string;
};
