// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * like PaginationCursor but for the person_content_combined table
 */
export type PersonContentCombinedPaginationCursor = string;
