// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { PersonId } from "./PersonId";

export interface PersonAggregates {
  id: number;
  person_id: PersonId;
  post_count: /* integer */ number;
  post_score: /* integer */ number;
  comment_count: /* integer */ number;
  comment_score: /* integer */ number;
}
