// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { NotificationId } from "./NotificationId";
import type { NotificationTypes } from "./NotificationTypes";
import type { PersonId } from "./PersonId";

export type PersonNotification = {
  notification_id: NotificationId;
  recipient_id: PersonId;
  kind: NotificationTypes;
  read: boolean;
};
