// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Comment } from "./Comment";
import type { Community } from "./Community";
import type { Person } from "./Person";
import type { PersonCommentMention } from "./PersonCommentMention";
import type { Post } from "./Post";
import type { SubscribedType } from "./SubscribedType";

/**
 * A person comment mention view.
 */
export type PersonCommentMentionView = {
  person_comment_mention: PersonCommentMention;
  comment: Comment;
  creator: Person;
  post: Post;
  community: Community;
  recipient: Person;
  creator_banned_from_community: boolean;
  banned_from_community: boolean;
  creator_is_moderator: boolean;
  creator_is_admin: boolean;
  subscribed: SubscribedType;
  saved: boolean;
  creator_blocked: boolean;
  my_vote?: number;
};
