// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * The person sort type.
 */
export type PersonSortType = "new" | "old" | "post_score" | "comment_score";
