// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Person } from "./Person";
import type { PersonAggregates } from "./PersonAggregates";

/**
 * A person view.
 */
export type PersonView = {
  person: Person;
  counts: PersonAggregates;
  is_admin: boolean;
};
