// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { InstanceActions } from "./InstanceActions";
import type { Person } from "./Person";
import type { PersonActions } from "./PersonActions";

/**
 * A person view.
 */
export type PersonView = {
  person: Person;
  is_admin: boolean;
  person_actions?: PersonActions;
  home_instance_actions?: InstanceActions;
  local_instance_actions?: InstanceActions;
  creator_banned: boolean;
};
