// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { PersonView } from "./PersonView";

/**
 * A person response for actions done to a person.
 */
export type PersonResponse = { person_view: PersonView };
