// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CommentId } from "./CommentId";
import type { PersonCommentMentionId } from "./PersonCommentMentionId";
import type { PersonId } from "./PersonId";

/**
 * A person mention.
 */
export type PersonCommentMention = {
  id: PersonCommentMentionId;
  recipient_id: PersonId;
  comment_id: CommentId;
  read: boolean;
  published_at: string;
};
