// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { PersonId } from "./PersonId";

/**
 * Aggregate data for a person.
 */
export type PersonAggregates = {
  person_id: PersonId;
  post_count: number;
  comment_count: number;
  published: string;
};
