// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CommentView } from "./CommentView";
import type { PostView } from "./PostView";

export type PersonContentCombinedView =
  | ({ type_: "post" } & PostView)
  | ({ type_: "comment" } & CommentView);
