// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type PostActions = {
  /**
   * When the post was read.
   */
  read_at?: string;
  /**
   * When was the last time you read the comments.
   */
  read_comments_at?: string;
  /**
   * The number of comments you read last. Subtract this from total comments to get an unread
   * count.
   */
  read_comments_amount?: bigint;
  /**
   * When the post was saved.
   */
  saved_at?: string;
  /**
   * When the post was liked.
   */
  liked_at?: string;
  /**
   * The like / score of the post.
   */
  like_score?: number;
  /**
   * When the post was hidden.
   */
  hidden_at?: string;
};
