// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A post-view mode that changes how multiple post listings look.
 */
export type PostListingMode = "list" | "card" | "small_card";
