// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Comment } from "./Comment";
import type { Post } from "./Post";
import type { PrivateMessage } from "./PrivateMessage";

export type PostOrCommentOrPrivateMessage =
  | ({ type_: "Post" } & Post)
  | ({ type_: "Comment" } & Comment)
  | ({ type_: "PrivateMessage" } & PrivateMessage);
