// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Available settings for post notifications
 */
export type PostNotificationsMode =
  | "all_comments"
  | "replies_and_mentions"
  | "mute";
