// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * The post sort types. See here for descriptions: https://join-lemmy.org/docs/en/users/03-votes-and-ranking.html
 */
export type PostSortType =
  | "Active"
  | "Hot"
  | "New"
  | "Old"
  | "Top"
  | "MostComments"
  | "NewComments"
  | "Controversial"
  | "Scaled";
