// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { PostId } from "./PostId";

export interface PostAggregates {
  id: number;
  post_id: PostId;
  comments: number;
  score: number;
  upvotes: number;
  downvotes: number;
  published: string;
  newest_comment_time_necro: string;
  newest_comment_time: string;
  featured_community: boolean;
  featured_local: boolean;
  hot_rank: number;
  hot_rank_active: number;
  controversy_rank: number;
}
