// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Lets you show votes for others only, show all votes, or hide all votes.
 */
export type PostNotificationsMode =
  | "AllComments"
  | "RepliesAndMentions"
  | "Mute";
