// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { PostId } from "./PostId";

export interface PostAggregates {
  id: number;
  post_id: PostId;
  comments: /* integer */ number;
  score: /* integer */ number;
  upvotes: /* integer */ number;
  downvotes: /* integer */ number;
  published: string;
}
