// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { PersonId } from "./PersonId";
import type { PostId } from "./PostId";

export type PostActions = {
  post_id: PostId;
  person_id: PersonId;
  read?: string;
  read_comments?: string;
  read_comments_amount?: number;
  saved?: string;
  liked?: string;
  like_score?: number;
  hidden?: string;
};
