// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Person } from "./Person";
import type { PrivateMessage } from "./PrivateMessage";
import type { PrivateMessageReport } from "./PrivateMessageReport";

/**
 * A private message report view.
 */
export type PrivateMessageReportView = {
  private_message_report: PrivateMessageReport;
  private_message: PrivateMessage;
  creator: Person;
  private_message_creator: Person;
  resolver?: Person;
};
