// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { PrivateMessageView } from "./PrivateMessageView";

/**
 * The private messages response.
 */
export type PrivateMessagesResponse = {
  private_messages: Array<PrivateMessageView>;
};
