// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { PersonId } from "./PersonId";
import type { PrivateMessageId } from "./PrivateMessageId";
import type { PrivateMessageReportId } from "./PrivateMessageReportId";

/**
 * The private message report.
 */
export type PrivateMessageReport = {
  id: PrivateMessageReportId;
  creator_id: PersonId;
  private_message_id: PrivateMessageId;
  /**
   * The original text.
   */
  original_pm_text: string;
  reason: string;
  resolved: boolean;
  resolver_id?: PersonId;
  published: string;
  updated?: string;
};
