// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { PrivateMessageView } from "./PrivateMessageView";

export interface PrivateMessageResponse {
  private_message_view: PrivateMessageView;
}
