// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Person } from "./Person";
import type { PrivateMessage } from "./PrivateMessage";
import type { PrivateMessageReport } from "./PrivateMessageReport";

export interface PrivateMessageReportView {
  private_message_report: PrivateMessageReport;
  private_message: PrivateMessage;
  private_message_creator: Person;
  creator: Person;
  resolver?: Person;
}
