// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Person } from "./Person";
import type { PrivateMessage } from "./PrivateMessage";

/**
 * A private message view.
 */
export type PrivateMessageView = {
  private_message: PrivateMessage;
  creator: Person;
  recipient: Person;
};
