// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { DbUrl } from "./DbUrl";
import type { PersonId } from "./PersonId";
import type { PrivateMessageId } from "./PrivateMessageId";

/**
 * A private message.
 */
export type PrivateMessage = {
  id: PrivateMessageId;
  creator_id: PersonId;
  recipient_id: PersonId;
  content: string;
  deleted: boolean;
  read: boolean;
  published: string;
  updated?: string;
  ap_id: DbUrl;
  local: boolean;
  removed: boolean;
};
