// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { PrivateMessageReportView } from "./PrivateMessageReportView";

/**
 * A private message report response.
 */
export type PrivateMessageReportResponse = {
  private_message_report_view: PrivateMessageReportView;
};
