// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { OAuthProviderId } from "./OAuthProviderId";

export type PublicOAuthProvider = {
  id: OAuthProviderId;
  /**
   * The OAuth 2.0 provider name displayed to the user on the Login page
   */
  display_name: string;
  /**
   * The authorization endpoint is used to interact with the resource owner and obtain an
   * authorization grant. This is usually provided by the OAUTH provider.
   */
  authorization_endpoint: string;
  /**
   * The client_id is provided by the OAuth 2.0 provider and is a unique identifier to this
   * service
   */
  client_id: string;
  /**
   * Lists the scopes requested from users. Users will have to grant access to the requested scope
   * at sign up.
   */
  scopes: string;
  /**
   * switch to enable or disable PKCE
   */
  use_pkce: boolean;
};
