// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CommentId } from "./CommentId";

export interface PurgeComment {
  comment_id: CommentId;
  reason?: string;
  auth: string;
}
