// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { PostId } from "./PostId";

/**
 * Purges a post from the database. This will delete all content attached to that post.
 */
export type PurgePost = { post_id: PostId; reason?: string };
