// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { PersonId } from "./PersonId";

/**
 * Purges a person from the database. This will delete all content attached to that person.
 */
export type PurgePerson = { person_id: PersonId; reason?: string };
