// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CommunityId } from "./CommunityId";

/**
 * Purges a community from the database. This will delete all content attached to that community.
 */
export type PurgeCommunity = { community_id: CommunityId; reason?: string };
