// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CommentId } from "./CommentId";

/**
 * Purges a comment from the database. This will delete all content attached to that comment.
 */
export type PurgeComment = { comment_id: CommentId; reason?: string };
