// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * The registration application id.
 */
export type RegistrationApplicationId = number;
