// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export interface Register {
  username: string;
  password: string;
  password_verify: string;
  show_nsfw: boolean;
  email?: string;
  captcha_uuid?: string;
  captcha_answer?: string;
  honeypot?: string;
  answer?: string;
}
