// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * The registration mode for your site. Determines what happens after a user signs up.
 */
export type RegistrationMode = "closed" | "require_application" | "open";
