// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CommentId } from "./CommentId";

/**
 * Remove a comment (only doable by mods).
 */
export type RemoveComment = {
  comment_id: CommentId;
  removed: boolean;
  reason: string;
  /**
   * Setting this will override whatever `removed` was set to,
   * leave as null or unset to act just on the comment itself.
   */
  remove_children?: boolean;
};
