// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { PostId } from "./PostId";

/**
 * Remove a post (only doable by mods).
 */
export type RemovePost = { post_id: PostId; removed: boolean; reason?: string };
