// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { PostId } from "./PostId";

/**
 * Remove a post (only doable by mods).
 */
export type RemovePost = {
  post_id: PostId;
  removed: boolean;
  reason: string;
  /**
   * Setting this will override whatever `removed` was set to,
   * leave as null or unset to act just on the post itself.
   */
  remove_children?: boolean;
};
