// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CommunityId } from "./CommunityId";

export interface RemoveCommunity {
  community_id: CommunityId;
  removed: boolean;
  reason?: string;
  expires?: number;
  auth: string;
}
