// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A list of possible types for reports.
 */
export type ReportType =
  | "All"
  | "Posts"
  | "Comments"
  | "PrivateMessages"
  | "Communities";
