// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CommentReportId } from "./CommentReportId";
import type { PostReportId } from "./PostReportId";
import type { PrivateMessageReportId } from "./PrivateMessageReportId";
import type { ReportCombinedId } from "./ReportCombinedId";

/**
 * A combined reports table.
 */
export type ReportCombined = {
  id: ReportCombinedId;
  published: string;
  post_report_id?: PostReportId;
  comment_report_id?: CommentReportId;
  private_message_report_id?: PrivateMessageReportId;
};
