// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CommentReportView } from "./CommentReportView";
import type { CommunityReportView } from "./CommunityReportView";
import type { PostReportView } from "./PostReportView";
import type { PrivateMessageReportView } from "./PrivateMessageReportView";

export type ReportCombinedView =
  | ({ type_: "post" } & PostReportView)
  | ({ type_: "comment" } & CommentReportView)
  | ({ type_: "private_message" } & PrivateMessageReportView)
  | ({ type_: "community" } & CommunityReportView);
