// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { PrivateMessageReportId } from "./PrivateMessageReportId";

export interface ResolvePrivateMessageReport {
  report_id: PrivateMessageReportId;
  resolved: boolean;
  auth: string;
}
