// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CommentView } from "./CommentView";
import type { CommunityView } from "./CommunityView";
import type { MultiCommunityView } from "./MultiCommunityView";
import type { PersonView } from "./PersonView";
import type { PostView } from "./PostView";

export type ResolveObjectView =
  | ({ type_: "post" } & PostView)
  | ({ type_: "comment" } & CommentView)
  | ({ type_: "person" } & PersonView)
  | ({ type_: "community" } & CommunityView)
  | ({ type_: "multi_community" } & MultiCommunityView);
