// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Does an apub fetch for an object.
 */
export type ResolveObject = {
  /**
   * Can be the full url, or a shortened version like: !fediverse@lemmy.ml
   */
  q: string;
};
