// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CommentReportId } from "./CommentReportId";

/**
 * Resolve a comment report (only doable by mods).
 */
export type ResolveCommentReport = {
  report_id: CommentReportId;
  resolved: boolean;
};
