// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * The type of content returned from a search.
 */
export type SearchType =
  | "all"
  | "comments"
  | "posts"
  | "communities"
  | "users"
  | "multi_communities";
