// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { SearchCombinedView } from "./SearchCombinedView";

/**
 * The search response, containing lists of the return type possibilities
 */
export type SearchResponse = { results: Array<SearchCombinedView> };
