// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * like PaginationCursor but for the modlog_combined
 */
export type SearchCombinedPaginationCursor = string;
