// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CommentView } from "./CommentView";
import type { CommunityView } from "./CommunityView";
import type { MultiCommunity } from "./MultiCommunity";
import type { PersonView } from "./PersonView";
import type { PostView } from "./PostView";

export type SearchCombinedView =
  | ({ type_: "Post" } & PostView)
  | ({ type_: "Comment" } & CommentView)
  | ({ type_: "Community" } & CommunityView)
  | ({ type_: "Person" } & PersonView)
  | ({ type_: "MultiCommunity" } & MultiCommunity);
