// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { SiteView } from "./SiteView";

/**
 * The response for a site.
 */
export type SiteResponse = {
  site_view: SiteView;
  /**
   * deprecated, use field `tagline` or /api/v3/tagline/list
   */
  taglines: Array<null>;
};
