// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { SiteView } from "./SiteView";
import type { Tagline } from "./Tagline";

export interface SiteResponse {
  site_view: SiteView;
  taglines: Array<Tagline>;
}
