// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { SiteId } from "./SiteId";

export interface SiteAggregates {
  site_id: SiteId;
  users: number;
  posts: number;
  comments: number;
  communities: number;
  users_active_day: number;
  users_active_week: number;
  users_active_month: number;
  users_active_half_year: number;
}
