// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A type / status for a community subscribe.
 */
export type SubscribedType =
  | "Subscribed"
  | "NotSubscribed"
  | "Pending"
  | "ApprovalRequired";
