// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A response that completes successfully.
 */
export type SuccessResponse = { success: boolean };
