// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { LocalSiteId } from "./LocalSiteId";

export interface Tagline {
  id: number;
  local_site_id: LocalSiteId;
  content: string;
  published: string;
  updated?: string;
}
