// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A tagline, shown at the top of your site.
 */
export type Tagline = {
  id: number;
  content: string;
  published: string;
  updated?: string;
};
