// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { TaglineId } from "./TaglineId";

/**
 * A tagline, shown at the top of your site.
 */
export type Tagline = {
  id: TaglineId;
  content: string;
  published_at: string;
  updated_at?: string;
};
