// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CommunityId } from "./CommunityId";
import type { PersonId } from "./PersonId";

/**
 * Transfer a community to a new owner.
 */
export type TransferCommunity = {
  community_id: CommunityId;
  person_id: PersonId;
};
