// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Contains the amount of unread items of various types. For normal users this means the number of
 * unread notifications, mods and admins get additional unread counts for reports, registration
 * applications and pending follows to private communities.
 */
export type UnreadCountsResponse = {
  notification_count: number;
  report_count?: number;
  pending_follow_count?: number;
  registration_application_count?: number;
};
