// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * These errors are only used for federation or internally and dont need to be translated.
 */
export type UntranslatedError =
  | "InvalidCommunity"
  | "CannotCreatePostOrCommentInDeletedOrRemovedCommunity"
  | "CannotReceivePage"
  | "OnlyLocalAdminCanRemoveCommunity"
  | "OnlyLocalAdminCanRestoreCommunity"
  | "PostIsLocked"
  | { PersonIsBannedFromSite: string }
  | "InvalidVoteValue"
  | "PageDoesNotSpecifyCreator"
  | "FederationDisabled"
  | { DomainBlocked: string }
  | { DomainNotInAllowList: string }
  | "FederationDisabledByStrictAllowList"
  | "ContradictingFilters"
  | "UrlWithoutDomain"
  | "InboxTimeout"
  | "CantDeleteSite"
  | "ObjectIsNotPublic"
  | "ObjectIsNotPrivate"
  | { InvalidFollow: string }
  | "PurgeInvalidImageUrl"
  | "Unreachable"
  | "CouldntSendWebmention"
  | { CommunityHasNoFollowers: string };
