// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * These errors are only used for federation or internally and dont need to be translated.
 */
export type UntranslatedError =
  | { error: "invalid_community" }
  | { error: "cannot_create_post_or_comment_in_deleted_or_removed_community" }
  | { error: "cannot_receive_page" }
  | { error: "only_local_admin_can_remove_community" }
  | { error: "only_local_admin_can_restore_community" }
  | { error: "post_is_locked" }
  | { error: "person_is_banned_from_site"; message: string }
  | { error: "invalid_vote_value" }
  | { error: "page_does_not_specify_creator" }
  | { error: "federation_disabled" }
  | { error: "domain_blocked"; message: string }
  | { error: "domain_not_in_allow_list"; message: string }
  | { error: "federation_disabled_by_strict_allow_list" }
  | { error: "contradicting_filters" }
  | { error: "url_without_domain" }
  | { error: "inbox_timeout" }
  | { error: "cant_delete_site" }
  | { error: "object_is_not_public" }
  | { error: "object_is_not_private" }
  | { error: "invalid_follow"; message: string }
  | { error: "purge_invalid_image_url" }
  | { error: "unreachable" }
  | { error: "couldnt_send_webmention" }
  | { error: "community_has_no_followers"; message: string };
