// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { TaglineId } from "./TaglineId";

/**
 * Update a tagline
 */
export type UpdateTagline = { id: TaglineId; content: string };
