// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { PostId } from "./PostId";
import type { TagId } from "./TagId";

/**
 * Update tags for a post.
 */
export type UpdatePostTags = { post_id: PostId; tags: Array<TagId> };
