// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { PostId } from "./PostId";
import type { PostNotificationsMode } from "./PostNotificationsMode";

/**
 * Disable reply notifications for a post and all comments inside it
 */
export type UpdatePostNotifications = {
  post_id: PostId;
  mode: PostNotificationsMode;
};
