// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CommunityId } from "./CommunityId";
import type { CommunityNotificationsMode } from "./CommunityNotificationsMode";

/**
 * Disable reply notifications for a post and all comments inside it
 */
export type UpdateCommunityNotifications = {
  community_id: CommunityId;
  mode: CommunityNotificationsMode;
};
