// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { InstanceId } from "./InstanceId";

/**
 * Block an instance's communities.
 */
export type UserBlockInstanceCommunitiesParams = {
  instance_id: InstanceId;
  block: boolean;
};
