// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CommentId } from "./CommentId";
import type { Person } from "./Person";

export type VoteViewComment = {
  creator: Person;
  creator_banned: boolean;
  creator_banned_from_community: boolean;
  is_upvote: boolean;
  comment_id: CommentId;
};
