// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Person } from "./Person";

/**
 * A vote view for checking a post or comments votes.
 */
export type VoteView = {
  creator: Person;
  creator_banned: boolean;
  creator_banned_from_community: boolean;
  is_upvote: boolean;
};
